/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        dark: {
          DEFAULT: '#09090b',
          50: '#f4f4f5',
          100: '#e4e4e7',
          200: '#d4d4d8',
          300: '#a1a1aa',
          400: '#71717a',
          500: '#52525b',
          600: '#3f3f46',
          700: '#27272a',
          800: '#18181b',
          900: '#09090b',
          950: '#030303',
        },
        primary: {
          DEFAULT: '#8b5cf6',
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        secondary: {
          DEFAULT: '#06b6d4',
          50: '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          700: '#0e7490',
          800: '#155e75',
          900: '#164e63',
        },
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        surface: {
          DEFAULT: 'rgba(24, 24, 27, 0.8)',
          hover: 'rgba(39, 39, 42, 0.8)',
        },
        card: '#18181b',
        textPrimary: '#fafafa',
        textSecondary: '#a1a1aa',
        textMuted: '#71717a',
        paper: {
          DEFAULT: '#f6f1e5',
          dim: '#efe7d3',
          dark: '#e7dcc3',
        },
        ink: {
          DEFAULT: '#16130e',
          soft: '#3a3428',
        },
        retro: {
          yellow: '#ffbe0b',
          orange: '#fb5607',
          pink: '#ff5d8f',
          purple: '#8338ec',
          blue: '#3a86ff',
          cyan: '#00b4d8',
          green: '#06d6a0',
          red: '#ef476f',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        'display-retro': ['"Archivo Black"', 'sans-serif'],
        pixel: ['"Press Start 2P"', 'monospace'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'gradient': 'gradient 8s ease infinite',
        'spin-slow': 'spin 20s linear infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'shimmer': 'shimmer 2s linear infinite',
        'bounce-soft': 'bounceSoft 2s ease-in-out infinite',
        'orb': 'orb 8s ease-in-out infinite',
        'pulse-ring': 'pulseRing 1.5s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        'typing': 'typing 3.5s steps(40, end)',
        'blink-caret': 'blink-caret 0.75s step-end infinite',
        'spin-slow-rev': 'spin 25s linear infinite reverse',
        'float-gentle': 'floatGentle 10s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite alternate',
        'slide-right': 'slideRight 0.5s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'bounce-in': 'bounceIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'float-bounce': 'floatBounce 3s ease-in-out infinite',
        'morph': 'morph 15s ease-in-out infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'aurora': 'aurora 15s ease-in-out infinite',
        'aurora-2': 'aurora2 18s ease-in-out infinite',
        'aurora-3': 'aurora3 22s ease-in-out infinite',
        'shimmer-text': 'shimmerText 3s ease-in-out infinite',
        'border-flow': 'borderFlow 6s ease infinite',
        'float-y': 'floatY 6s ease-in-out infinite',
        'particle-drift': 'particleDrift 20s linear infinite',
        'counter-bounce': 'counterBounce 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'glow-ring': 'glowRing 2s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'tada': 'tada 1s ease-in-out',
        'flip': 'flip 0.6s ease-in-out',
        'rubber-band': 'rubberBand 1s ease-in-out',
        'shake': 'shake 0.5s ease-in-out',
        'swing': 'swing 1s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px -5px rgba(139, 92, 246, 0.4)' },
          '50%': { boxShadow: '0 0 40px -5px rgba(139, 92, 246, 0.8)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        orb: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%': { transform: 'translate(10px, -20px) scale(1.05)' },
          '50%': { transform: 'translate(-5px, 10px) scale(0.95)' },
          '75%': { transform: 'translate(-15px, -5px) scale(1.02)' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.8)', opacity: '1' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        typing: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        'blink-caret': {
          '0%, 100%': { 'border-color': 'transparent' },
          '50%': { 'border-color': 'currentColor' },
        },
        floatGentle: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(-15px) rotate(2deg)' },
          '66%': { transform: 'translateY(-8px) rotate(-1deg)' },
        },
        glowPulse: {
          '0%': { boxShadow: '0 0 5px rgba(139, 92, 246, 0.5), 0 0 10px rgba(139, 92, 246, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(139, 92, 246, 0.8), 0 0 40px rgba(139, 92, 246, 0.4)' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        floatBounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        morph: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
        },
        ping: {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
        aurora: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1) rotate(0deg)' },
          '25%': { transform: 'translate(100px, -60px) scale(1.2) rotate(90deg)' },
          '50%': { transform: 'translate(-50px, 40px) scale(0.9) rotate(180deg)' },
          '75%': { transform: 'translate(60px, -30px) scale(1.1) rotate(270deg)' },
        },
        aurora2: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(-80px, 50px) scale(1.15)' },
          '66%': { transform: 'translate(60px, -40px) scale(0.9)' },
        },
        aurora3: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1) rotate(0deg)' },
          '50%': { transform: 'translate(-40px, -30px) scale(1.1) rotate(180deg)' },
        },
        shimmerText: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        borderFlow: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        floatY: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        particleDrift: {
          '0%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translate(100vw, -100vh) rotate(720deg)', opacity: '0' },
        },
        counterBounce: {
          '0%': { transform: 'scale(0)' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
        glowRing: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(139, 92, 246, 0.4)' },
          '50%': { boxShadow: '0 0 0 15px rgba(139, 92, 246, 0)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.3)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.3)' },
          '70%': { transform: 'scale(1)' },
        },
        tada: {
          '0%': { transform: 'scale(1) rotate(0deg)' },
          '10%, 20%': { transform: 'scale(0.9) rotate(-3deg)' },
          '30%, 50%, 70%, 90%': { transform: 'scale(1.1) rotate(3deg)' },
          '40%, 60%, 80%': { transform: 'scale(1.1) rotate(-3deg)' },
          '100%': { transform: 'scale(1) rotate(0deg)' },
        },
        flip: {
          '0%': { transform: 'perspective(400px) rotateY(0)' },
          '40%': { transform: 'perspective(400px) rotateY(-180deg)' },
          '100%': { transform: 'perspective(400px) rotateY(0)' },
        },
        rubberBand: {
          '0%': { transform: 'scale(1)' },
          '30%': { transform: 'scaleX(1.25) scaleY(0.75)' },
          '40%': { transform: 'scaleX(0.75) scaleY(1.25)' },
          '50%': { transform: 'scaleX(1.15) scaleY(0.85)' },
          '65%': { transform: 'scaleX(0.95) scaleY(1.05)' },
          '75%': { transform: 'scaleX(1.05) scaleY(0.95)' },
          '100%': { transform: 'scale(1)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        swing: {
          '20%': { transform: 'rotate(15deg)' },
          '40%': { transform: 'rotate(-10deg)' },
          '60%': { transform: 'rotate(5deg)' },
          '80%': { transform: 'rotate(-5deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        marqueeReverse: {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        },
        starburstSpin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        stickerFloat: {
          '0%, 100%': { transform: 'translateY(0) rotate(var(--sticker-rotate, -4deg))' },
          '50%': { transform: 'translateY(-10px) rotate(var(--sticker-rotate, -4deg))' },
        },
        stampIn: {
          '0%': { transform: 'scale(2.2) rotate(-18deg)', opacity: '0' },
          '60%': { transform: 'scale(0.92) rotate(-10deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(-12deg)', opacity: '1' },
        },
        caretBlink: {
          '0%, 49%': { opacity: '1' },
          '50%, 100%': { opacity: '0' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'mesh-gradient': 'linear-gradient(135deg, rgba(139, 92, 246, 0.1) 0%, rgba(6, 182, 212, 0.1) 50%, rgba(236, 72, 153, 0.1) 100%)',
        'gradient-primary': 'linear-gradient(135deg, #8b5cf6 0%, #06b6d4 100%)',
        'gradient-dark': 'linear-gradient(180deg, #09090b 0%, #18181b 100%)',
        'gradient-mesh': 'radial-gradient(at 40% 20%, rgba(139, 92, 246, 0.15) 0px, transparent 50%), radial-gradient(at 80% 0%, rgba(6, 182, 212, 0.1) 0px, transparent 50%), radial-gradient(at 0% 50%, rgba(236, 72, 153, 0.1) 0px, transparent 50%), radial-gradient(at 80% 50%, rgba(139, 92, 246, 0.1) 0px, transparent 50%), radial-gradient(at 0% 100%, rgba(6, 182, 212, 0.1) 0px, transparent 50%)',
      },
      boxShadow: {
        'glow-purple': '0 0 40px -5px rgba(139, 92, 246, 0.5)',
        'glow-cyan': '0 0 40px -5px rgba(6, 182, 212, 0.5)',
        'glow-pink': '0 0 40px -5px rgba(236, 72, 153, 0.5)',
        'glow-soft': '0 8px 32px rgba(0, 0, 0, 0.4)',
        'glow-intense': '0 0 60px -10px rgba(139, 92, 246, 0.7)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        'inner-glow': 'inset 0 0 20px rgba(139, 92, 246, 0.1)',
        'glow-green': '0 0 40px -5px rgba(16, 185, 129, 0.5)',
        'glow-yellow': '0 0 40px -5px rgba(245, 158, 11, 0.5)',
        'glow-red': '0 0 40px -5px rgba(239, 68, 68, 0.5)',
        'glow-primary': '0 0 30px -5px rgba(139, 92, 246, 0.6)',
        'glow-secondary': '0 0 30px -5px rgba(6, 182, 212, 0.6)',
        'neo-sm': '0 2px 10px rgba(0, 0, 0, 0.3)',
        'neo-md': '0 4px 20px rgba(0, 0, 0, 0.4)',
        'neo-lg': '0 8px 40px rgba(0, 0, 0, 0.5)',
        'inner-light': 'inset 0 0 30px rgba(255, 255, 255, 0.05)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.6)',
        'retro-sm': '2px 2px 0 0 #16130e',
        'retro': '4px 4px 0 0 #16130e',
        'retro-md': '6px 6px 0 0 #16130e',
        'retro-lg': '8px 8px 0 0 #16130e',
        'retro-xl': '12px 12px 0 0 #16130e',
        'retro-yellow': '4px 4px 0 0 #ffbe0b',
        'retro-pink': '4px 4px 0 0 #ff5d8f',
        'retro-blue': '4px 4px 0 0 #3a86ff',
        'retro-green': '4px 4px 0 0 #06d6a0',
        'retro-white': '4px 4px 0 0 #f6f1e5',
      },
      backdropBlur: {
        xs: '2px',
        '2xl': '40px',
        '3xl': '64px',
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
      },
      transitionTimingFunction: {
        'bounce-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
      screens: {
        'xs': '375px',
        '3xl': '1920px',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'gradient': 'gradient 8s ease infinite',
        'spin-slow': 'spin 20s linear infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'shimmer': 'shimmer 2s linear infinite',
        'bounce-soft': 'bounceSoft 2s ease-in-out infinite',
        'orb': 'orb 8s ease-in-out infinite',
        'pulse-ring': 'pulseRing 1.5s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        'typing': 'typing 3.5s steps(40, end)',
        'blink-caret': 'blink-caret 0.75s step-end infinite',
        'spin-slow-rev': 'spin 25s linear infinite reverse',
        'float-gentle': 'floatGentle 10s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite alternate',
        'slide-right': 'slideRight 0.5s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'bounce-in': 'bounceIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'float-bounce': 'floatBounce 3s ease-in-out infinite',
        'morph': 'morph 15s ease-in-out infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'aurora': 'aurora 15s ease-in-out infinite',
        'aurora-2': 'aurora2 18s ease-in-out infinite',
        'aurora-3': 'aurora3 22s ease-in-out infinite',
        'shimmer-text': 'shimmerText 3s ease-in-out infinite',
        'border-flow': 'borderFlow 6s ease infinite',
        'float-y': 'floatY 6s ease-in-out infinite',
        'particle-drift': 'particleDrift 20s linear infinite',
        'counter-bounce': 'counterBounce 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'glow-ring': 'glowRing 2s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'tada': 'tada 1s ease-in-out',
        'flip': 'flip 0.6s ease-in-out',
        'rubber-band': 'rubberBand 1s ease-in-out',
        'shake': 'shake 0.5s ease-in-out',
        'swing': 'swing 1s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'fade-in-left': 'fadeInLeft 0.6s ease-out forwards',
        'fade-in-right': 'fadeInRight 0.6s ease-out forwards',
        'scale-up': 'scaleUp 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'slide-in-up': 'slideInUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in-down': 'slideInDown 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'blur-in': 'blurIn 0.5s ease-out forwards',
        'magnetic': 'magnetic 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'glow-rotate': 'glowRotate 20s linear infinite',
        'morph-blob': 'morphBlob 8s ease-in-out infinite',
        'float-3d': 'float3d 6s ease-in-out infinite',
        'marquee': 'marquee 24s linear infinite',
        'marquee-slow': 'marquee 40s linear infinite',
        'marquee-reverse': 'marqueeReverse 32s linear infinite',
        'starburst': 'starburstSpin 14s linear infinite',
        'starburst-slow': 'starburstSpin 30s linear infinite',
        'sticker': 'stickerFloat 5s ease-in-out infinite',
        'stamp': 'stampIn 0.45s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'caret': 'caretBlink 1.1s step-end infinite',
      },
    },
  },
  plugins: [],
};
