import React, { useEffect } from 'react';
import { VerdictData } from '../data/demoData';

export const PdfView: React.FC<{ verdict: VerdictData, onBack: () => void }> = ({ verdict, onBack }) => {
  useEffect(() => {
    // Small delay to allow render before print dialog
    const timer = setTimeout(() => {
      window.print();
    }, 500);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="bg-white min-h-screen text-black p-8 font-sans max-w-4xl mx-auto">
      {/* Non-printable back button */}
      <div className="print:hidden mb-8">
        <button onClick={onBack} className="text-blue-600 hover:underline">← Back to Dashboard</button>
      </div>

      <header className="border-b-2 border-gray-200 pb-6 mb-8">
        <h1 className="text-3xl font-bold mb-2">PR Autopilot Evaluation Report</h1>
        <p className="text-gray-500">Generated on {new Date().toLocaleString()}</p>
      </header>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 border-b pb-2">1. Overview</h2>
        <div className="flex gap-8">
          <div className="flex-1">
            <p className="font-bold text-gray-700">Overall Verdict</p>
            <p className={`text-2xl font-bold ${verdict.overall_verdict === 'Pass' ? 'text-green-600' : verdict.overall_verdict === 'Fail' ? 'text-red-600' : 'text-yellow-600'}`}>
              {verdict.overall_verdict.toUpperCase()}
            </p>
          </div>
          <div className="flex-1">
            <p className="font-bold text-gray-700">Confidence Score</p>
            <p className="text-2xl font-bold">{verdict.confidence}%</p>
          </div>
        </div>
        <p className="mt-4 text-gray-700">{verdict.summary}</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 border-b pb-2">2. Requirements Breakdown</h2>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="p-2 border">#</th>
              <th className="p-2 border">Requirement</th>
              <th className="p-2 border">Verdict</th>
              <th className="p-2 border">Confidence</th>
            </tr>
          </thead>
          <tbody>
            {verdict.requirements.map((req, idx) => (
              <tr key={req.id}>
                <td className="p-2 border">{idx + 1}</td>
                <td className="p-2 border">{req.text}</td>
                <td className="p-2 border font-bold">{req.verdict}</td>
                <td className="p-2 border">{req.confidence}%</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 border-b pb-2">3. Evidence & Tests</h2>
        {verdict.requirements.map((req, idx) => (
          <div key={req.id} className="mb-6 page-break-inside-avoid">
            <h3 className="font-bold mb-2">{idx + 1}. {req.text}</h3>
            <div className="mb-2">
              <span className="font-bold text-sm text-gray-600">Evidence:</span>
              <div className="bg-gray-50 p-2 text-sm font-mono border rounded mt-1">{req.evidence}</div>
            </div>
            <div>
              <span className="font-bold text-sm text-gray-600">Generated Test:</span>
              <pre className="bg-gray-50 p-2 text-sm font-mono border rounded mt-1 whitespace-pre-wrap">
                {req.test}
              </pre>
            </div>
          </div>
        ))}
      </section>

      <footer className="mt-12 pt-4 border-t text-center text-gray-400 text-sm">
        Generated by PR Autopilot ⚡
      </footer>
    </div>
  );
};
